#端口号
server:
  port: 9001
  #服务名
spring:
  application:
    name: consumer
  #Nacos Server 的地址
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: 43.143.106.57:8848
#      config:
#        server-addr: 43.143.106.57:8848
#        group: Group1-lushixiang
#        name: DataId1-lushixiang
#        file-extension: yaml

